URL = 'http://localhost:8000/'
ALL = 'all'
ENTERPRISES = 'enterprises/'
QUESTIONS = 'questions/'
RESPONDENTS = 'respondents/'
SOFTWARE_CATEGORIES = 'software_categories/'
SURVEY_ANSWERS = 'survey_answers/'
SURVEYS = 'surveys/'