"""empty message

Revision ID: 172c5147f7f0
Revises: a35bf4b2ae61
Create Date: 2025-06-06 20:13:41.528366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172c5147f7f0'
down_revision: Union[str, None] = 'a35bf4b2ae61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('enterprises_industry_id_fkey'), 'enterprises', type_='foreignkey')
    op.drop_table('industries')
    op.drop_column('enterprises', 'industry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enterprises', sa.Column('industry_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('enterprises_industry_id_fkey'), 'enterprises', 'industries', ['industry_id'], ['id'])
    op.create_table('industries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('industries_pkey')),
    sa.UniqueConstraint('name', name=op.f('industries_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
