"""empty message

Revision ID: 3aab4f7c03ef
Revises: 172c5147f7f0
Create Date: 2025-06-06 22:03:52.620087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aab4f7c03ef'
down_revision: Union[str, None] = '172c5147f7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
