"""empty message

Revision ID: 5ec49ac3a8f9
Revises: 
Create Date: 2025-06-08 01:01:52.523944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec49ac3a8f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('questions_number_key'), 'questions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('questions_number_key'), 'questions', ['number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
