"""empty message

Revision ID: f66480745069
Revises: 3aab4f7c03ef
Create Date: 2025-06-06 22:06:53.765657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66480745069'
down_revision: Union[str, None] = '3aab4f7c03ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'user_agent',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
