version: "3.9"

x-env: &env   
    env_file:
      - ${ENV_FILE:-.env}
services:
  db:  
    <<: [*env]
    image: postgres:17.4-alpine
    ports:
      - "5431:5432"
    volumes:
      - botdb-data:/var/lib/postgresql/data

  bot:
    <<: [*env]
    entrypoint: sh -c "alembic upgrade head || true && uvicorn main:app --host 0.0.0.0"
    build: .
    ports:
      - "80:8000"
    depends_on:
      - db
volumes:
  botdb-data: