from aiogram.fsm.state import State, StatesGroup

class SurveyStates(StatesGroup):
    consent = State()
    company_name = State()
    company_inn = State()
    full_name = State()
    position = State()
    phone_number = State()
    email = State()
    implementation_stage = State()
    pain_points_selection = State()
    pain_points_other = State()
    pain_points_functionality_details = State()
    pain_points_integration_details = State()
    pain_points_personnel_details = State()
    pain_points_compatibility_details = State()
    pain_points_costs_details = State()
    pain_points_support_details = State()
    main_barrier = State()
    direct_replacement = State()
    direct_replacement_details = State()
    pilot_testing = State()
    software_classes = State()
    software_classes_choose = State()  # Новое состояние для выбора классов ПО
    software_classes_details = State()
    event_interest = State()
    solution_help = State()